### PR TITLE
Replace proofreader with phpcs

### PR DESCRIPTION
**Pull request by nlisgo**

### CODE REVIEW

**Comment by nlisgo** [comment]
@lsh-0 I cannot recreate this locally. I am not sure how to clear this. Would appreciate another pair of eyes on this.

**Comment by giorgiosironi** [comment]
For the record, runs on the `elife-libraries--ci` Jenkins node.

**Comment by giorgiosironi** [comment]
From https://alfred.elifesciences.org/monitoring/nodes/elife-libraries--ci?part=graph&graph=usedMemory shows the node has 1GB, either this gets maxed out or there is a `php.ini` setting that tells the PHP interpreter to crash on a lower limit.

**Comment by lsh-0** [comment]
It's using `-1`, which I'm guessing means `all`.

The instance has 2GiB RAM and is idling at about ~500MiB, leaving about 1.5GiB for the linter to run. A lock is acquired on `elife-libraries--ci` before it is used, so there is probably only one job running at the time.

Taking a closer look it appears to be composer that is failing and not the linting. Composer has always been greedy this way. That said, 1.5GiB of ram should be enough for anyone :tm: . I've given your build a kick and it was successful this time, I guess it was just bad luck.

We're using composer 1.10.16 which was the latest when composer 2 was released. I checked the changelogs of the more recent versions of 1.10.x and there are no mentions of bugfixes regarding RAM. Composer 2 is supposedly less greedy but we will need more (some, any) testing before we switch over to it. We have a ticket here: https://github.com/elifesciences/issues/issues/6242

**Pull request merged**
